version: "3.1"

services:
  backend:
    container_name: order-bot-backend
    image: nodirshox/order_bot_backend:latest
    restart: always
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - HTTP_PORT=3000
      - CDN_URL=${CDN_URL}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
    ports:
      - "5000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.docker.network=ta_default"
    networks:
     - common_network
  bot:
    container_name: order-bot-telegram
    image: nodirshox/order_bot_telegram:latest
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
      - GROUP_ID=${GROUP_ID}
    ports:
      - "5001:3000"
networks:
 common_network:
  external: true
  name: common_network
  